### PR TITLE
Adding fpm support

### PR DESCRIPTION
**Pull request by samharrison7**
This builds on this PR for the BMI Fortran binding repo - https://github.com/csdms/bmi-fortran/pull/46 - to add support for fpm to this example repo too.

A few notes:
* This will only work after that aformentioned PR has been merged, because it is expected that the HEAD of the csdms/bmi-fortran repo will have fpm support (i.e. have an fpm.toml file).
* I had to make a fair few changes to get this to work, including:
  * Renaming `examples` and `tests` dirs to `example` and `test`. This wasn't strictly necessary but saved me listing all of the examples and tests explicitly (fpm autodiscovers examples and tests, but only if they are in `example` and `test` directories).
  * Removing hardcoded references to `.cfg` files in the source code for tests and examples, and instead getting paths to them via command line parameters. This was because I couldn't figure out a way to get fpm to copy the `.cfg` files to the exe directory for when the tests/examples were run. I modified the CMake builds to account for this too.
* Technically I split the repo into two fpm projects - one for the heat model itself, and another for the BMI heat model (which uses the heat model as a dependency). Hence two the `fpm.toml` files. This was largely because of this issue with fpm: https://github.com/fortran-lang/fpm/issues/919

### CODE REVIEW

**Comment by samharrison7** [comment]
Just to flag that I'm having issues babelizing this Fortran heat model example when it is built using fpm, so we might want to figure that out before merging this. I can babelize it successfully using a CMake built version, so it's definitely something going wrong with fpm.

The specific error is something to do with gfortran: `ImportError: .../pymt_heatf/lib/heatmodel.cpython-311-x86_64-linux-gnu.so: undefined symbol: _gfortran_st_close`. Perhaps gfortran's runtime isn't being linked properly. I will try and reproduce a simpler example to help figure it out.

**Comment by samharrison7** [comment]
I did a bit more digging into the gfortran issue. Fpm only compiles to static libraries at the moment (https://github.com/fortran-lang/fpm/discussions/655). If I instead take the `.o` files that fpm generates and compile them into a dynamic library, then this works as expected. E.g., after running `fpm build`:

```
$ gfortran -shared build/gfortran_<build-hash>/bmifheat/*heat*.o build/gfortran_<build-hash>/build*.o -o libbmiheatf.so
$ mv libbmiheatf.so $CONDA_PREFIX/lib/
```

If I use `nm` to look at the `libbmiheatf.a` that is generated by fpm, all of the gfortran symbols are undefined:

```
...
U _gfortran_arandom_r4
U _gfortran_os_error_at
U _gfortran_runtime_error
U _gfortran_runtime_error_at
U _gfortran_st_close
...
```

I don't really understand this - everything was compiled using the same gfortran (installed with Conda via the `fortran-compiler` package), and the gfortran runtime libraries are definitely installed. I should say my knowledge on this type of stuff is pretty sketchy, so I'm probably missing something obvious.

Anyway, with respect to this PR, I think the options are:
* Carry on but add a caveat/warning somewhere to be careful if using fpm to build Fortran libraries for the babelizer.
* Hold off merging until this is fixed, either by fpm adding shared library support, or figuring out the obvious thing that I've missed that will make this magically work :)

**Comment by samharrison7** [comment]
I just updated the path to the `example` dir (renamed from `examples`) in the GitHub workflow and so hopefully tests should now pass 🤞

**Comment by mdpiper** [comment]
👋 @samharrison7 -- I'm sorry I let this PR languish for so long. I finally have some time to look at BMI stuff again, so I'm working through it now.

**Review by mdpiper — APPROVED** [review]
Thank you, @samharrison7!

**Comment by mdpiper** [comment]
> Just to flag that I'm having issues babelizing this Fortran heat model example when it is built using fpm, so we might want to figure that out before merging this. I can babelize it successfully using a CMake built version, so it's definitely something going wrong with fpm.

We're planning to update *babelizer* soon, so we can address the issues  you've found with *fpm* then.

**Pull request merged**
